### ISSUE TITLE
Complete v1 of repo2docker template

### ISSUE THREAD

**Issue by maxrjones** [maxrjones/cookiecutter-repo2docker#1]
## TODO

- [ ] Add instructions for using template
- [ ] Add tests
- [ ] Configuration for R packages
- [ ] Configuration for apt packages
- [ ] Configuration for Julia packages
- [ ] Configuration for docker registry
- [ ] Configuration for PyPI packages
- [ ] Configuration for postBuild code
- [ ] Configuration for runtimes
- [ ] Configuration for nix packages
- [ ] Add explanation of prompts
